apiVersion: v1
kind: Service
metadata:
  name: {{ template "vernemq.fullname" . }}-master
  labels:
    app: {{ template "vernemq.name" . }}-master
    chart: {{ template "vernemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: {{ .Values.service.portSsl }}
      targetPort: mqttssl
      protocol: TCP
      name: mqttssl  
    - port: 8888
      targetPort: status
      protocol: TCP
      name: status
    - port: 44053
      name: epmd
      targetPort: epmd
      protocol: TCP 
  selector:
    app: {{ template "vernemq.name" . }}-master
    release: {{ .Release.Name }}
