apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "vernemq.fullname" . }}
  labels:
    app: {{ template "vernemq.name" . }}
    chart: {{ template "vernemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vernemq.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-vernemq-cluster",
            "image": "erlio/docker-vernemq:0.15.3",
            "command": ["bash", "-c", "
              set -ex\n
              cp -r /etc/vernemq/* /mnt/vernemq/\n
              H=`hostname`\n
              if [[ \"$H\" != \"vernemq-0\" ]]; then\n
                SEED=`getent hosts vernemq-0.vernemq | awk ''{ print $1 }''`\n
                if [[ \"$SEED\" != \"\" ]]; then\n
                  echo -eval \"\\\"vmq_server_cmd:node_join(''VerneMQ@${SEED}'')\\\"\" >> /mnt/vernemq/vm.args\n
                else\n
                  echo \"[warning] could not find host vernemq-0.vernemq. not joining a cluster!\"\n
                  exit 1\n
                fi\n
              fi\n
            "],
            "volumeMounts": [
              {"name": "conf", "mountPath": "/mnt/vernemq"}
            ]
          }]'
      labels:
        app: {{ template "vernemq.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
